# Generated by Django 6.0.1 on 2026-02-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_v4_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencysettings',
            options={'ordering': ['id'], 'verbose_name_plural': 'Agency settings'},
        ),
    ]
