# Generated by Django 6.0.1 on 2026-02-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_agencysettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='category',
            field=models.CharField(blank=True, choices=[('SALARY', 'راتب'), ('DAILY', 'يومي'), ('GENERAL', 'عام'), ('VOUCHER', 'وصل'), ('OWNER_WITHDRAWAL', 'سحب مالك')], max_length=20),
        ),
    ]
