# Generated by Django 6.0.1 on 2026-03-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_exchange_rate_on_quotation_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'معلق'), ('SUBMITTED', 'تم الإرسال'), ('ACCEPTED', 'موافق عليه'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20),
        ),
    ]
