# Generated by Django 6.0.1 on 2026-04-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_quotation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(db_index=True, max_length=7, unique=True)),
                ('opening_iqd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'db_table': 'api_monthly_opening_balance',
                'ordering': ['year_month'],
            },
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
